#### 1.1 Creating a Vector

In [ ]:
import numpy as np

# Row vector
row_vec = np.array([1,2,3])

# Column vector
col_vec = np.array([[1],
                    [2],
                    [3]])

#### 1.2 Creating a Matrix

In [5]:
# Two dimentional ndarray
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Dedicated matrix function
matrix = np.mat([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(matrix)
# This function to create matrix is not recommended over ndarray

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 1.3 Creating a Sparse Matrix

In [7]:
# Why and when to use sparse matrix - when you have a huge matrix having very few non-zero values, use sparse matrix, its very space efficient.

import numpy as np
from scipy import sparse
import sys

matrix = np.array(([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                    [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]]))

print(matrix)
print(sys.getsizeof(matrix))

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]]
232


In [8]:
sparse_matrix = sparse.csr_matrix(matrix)
print(sparse_matrix)
print(sys.getsizeof(sparse_matrix))

# There are different types of sparse matrices with meaningful differences, no sparse matrix is best. You should know why you
# are choosing one over another.

# Sparse matrix is space efficient 232 vs 56.

  (1, 1)	1
  (2, 0)	3
56


#### 1.4 Selecting elements

In [9]:
import numpy as np

vector = np.array([1,2,3,4,5,6,7,8,9])

'''
Selecting elements from 1-d array.
-Single element
-Subarray
    -Continuous
    -Discontinuous
'''

e = vector[3]
cont_array = vector[2:8]
discont_array = vector[2:9:2]

print(e)
print(cont_array)
print(discont_array)

4
[3 4 5 6 7 8]
[3 5 7 9]


In [17]:
'''
Selecting elements from 1-d array.
-Single element
-Subarray
    -Continuous
    -Discontinuous
'''
matrix = np.array([[1,2,3], 
                   [4,5,6], 
                   [7,8,9]])

# Single element, tuple containing index of each dimension.
print(matrix[0, 2])
print(matrix[(0, 2)])

# Subarray - continuous sequence, tuple containing (start, stop) for each dimension.
print(matrix[0:2, 1:2])

# Subarray - continuous sequence, tuple containing (start, stop) for each dimension.
print(matrix[0::1, 1::2])

3
3
[[2]
 [5]]
[[2]
 [5]
 [8]]


#### 1.5 Describing a Matrix

In [18]:
import numpy as np

matrix = np.array([[1,2,3], 
                   [4,5,6], 
                   [7,8,9]])

# Number of dimension
print(matrix.ndim)

# Shape of matrix
print(matrix.shape)

# Size of matrix - total number of items in matrix
print(matrix.size)

2
(3, 3)
9


#### 1.6 Applying Operations to Elements

In [19]:
# Ndarray functions by default perform elementwise operations, if you have written a custom function and you want
# to make it ndarray aware then use np.vectorize.

import numpy as np

data = np.array([[1,2,3], 
                 [4,5,6], 
                 [7,8,9]])

f = lambda x: x**2 + x - 5

vectorized_f = np.vectorize(f)

result_data = vectorized_f(data)

print(result_data)

[[-3  1  7]
 [15 25 37]
 [51 67 85]]


#### 1.7 Finding the Maximum and Minimum Values

In [20]:
import numpy as np

data = np.array([[1,2,3], 
                 [4,5,6], 
                 [7,8,9]])

# min element from every columns.
print(np.min(data, axis=0))

# min element from every row.
print(np.min(data, axis=1))

# min element from whole array.
print(np.min(data))

# For maximum use np.max 
np.max(data)

[1 2 3]
[1 4 7]
1


#### 1.8 Calculating the Average, Variance, and Standard Deviation

In [21]:
import numpy as np

data = np.array([[1,2,3], 
                 [4,5,6], 
                 [7,8,9]])

# Mean of the elements
print(np.mean(data))

# Varience of the elements
print(np.var(data))

# Standard deviation of the data
print(np.std(data))

# Use axis parameter in case you want to calculate the same for perticular dimension(row, columns)

5.0
6.666666666666667
2.581988897471611


#### 1.9 Reshaping Arrays

In [3]:
# Reshape - 1d to nd, nd to 1d, md to nd, nd to "as many as needed", "as many as needed" to nd.

import numpy as np

data = np.array([[1,2,3], 
                 [4,5,6], 
                 [7,8,9], 
                 [10,11,12]])

reshape_data = data.reshape(6, 2)

print(reshape_data)

new_data = data.reshape(3, -1)
# -1 means as many as needed.
print(new_data)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### 1.10 Transposing a Vector or Matrix

In [5]:
# In context of vector, transpose means converting row vector to column and vice versa.
data = np.array([[1,2,3], 
                 [4,5,6]])

print(data.T)

# Transpose vector
vector = np.array([[1,2,3,4,5]])

print(vector.T)

[[1 4]
 [2 5]
 [3 6]]
[[1]
 [2]
 [3]
 [4]
 [5]]


#### 1.11 Flattening a Matrix

In [7]:
data = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(data.flatten())

# Flatten using reshape function.
print(data.reshape(1, -1))

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5 6 7 8 9]]


#### 1.12 Finding the Rank of a Matrix

In [9]:
# Rank - number to linearly independent vectors in matrix.

data = np.array([[1,2,3], 
                 [4,5,6], 
                 [7,8,9], 
                 [10,11,12]])

rank = np.linalg.matrix_rank(data)

print(rank)

2


#### 1.13 Calculating the Determinant

In [10]:
# Determinant - a value associated with the square matrix, used for inverse calculation.
# Determinant requires matrix to be square in case of 2d matrix, in case of nd matrix, the last two dimensions
# should have same dimension.

data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

determinant = np.linalg.det(data)

print(determinant)

-9.51619735392994e-16


#### 1.14 Getting the Diagonal of a Matrix

In [12]:
# Getting diagonal elements of matrix.

data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

print(np.diagonal(data))

# How to choose a diagonal that is not main diagonal. Use offset parameter in the same function.

print(np.diagonal(data, offset=1))

print(np.diagonal(data, offset=-1))

[1 5 9]
[2 6]
[4 8]


#### 1.15 Calculating the Trace of a Matrix

In [15]:
# Trace - sum of diagonal elements of the matrix, as matrix has multiple diagonls, a matrix can have multiple trace.
data = np.array([[1,2,3], 
                 [4,5,6], 
                 [7,8,9], 
                 [10,11,12]])

print(np.trace(data))

print(np.trace(data, offset=1))

# Calculate trace using diagonal function.
print(sum(data.diagonal()))

15
8
15


#### 1.16 Finding Eigenvalues and Eigenvectors

In [26]:
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

eigvalue, eigvector = np.linalg.eig(data)

#print(eigvalue)
#print(eigvector)

# A v = λ v 
print()
print(data.dot(eigvector))
print()
print(eigvalue.dot(eigvector))


[[-3.73863537e+00  8.77649763e-01 -3.88578059e-16]
 [-8.46653421e+00  9.68877101e-02 -3.33066907e-16]
 [-1.31944331e+01 -6.83874343e-01 -7.21644966e-16]]

[ -3.15193256 -12.56821563   7.49157328]
